### ISSUE TITLE
Activities repeat themselves

### ISSUE THREAD

**Issue by bayramliaziz** [bexis/Module_ResourceManagement#216] opened 2022-01-31 09:37 UTC
- Add a resource that contains the Reason button
- Click the Reason button to see the list of activities

Result: 

There is more than one activity for the same name. Activities repeat themselves.
![err](https://user-images.githubusercontent.com/66725469/151770268-b4050246-ef55-4a02-b43f-2986033525ae.png)

**Comment by EleonoraPetzold** [comment] 2022-04-19 09:43
I can't reproduce this, in debugging and production mode everything is ok:

![image](https://user-images.githubusercontent.com/42029171/163976433-1286c9e2-f7f6-4c05-84ad-1e2de2a88a80.png)

I will close this issue. Please update your code and test it again.

**Closed by EleonoraPetzold** 2022-04-19 09:43 UTC
Labels: Type: bug, Priority: Medium
